"""Your changes

Revision ID: 00787eedb53f
Revises: f012063df819
Create Date: 2025-04-04 09:48:52.869607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00787eedb53f'
down_revision: Union[str, None] = 'f012063df819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cash_account_name_per_account', 'cash_account', ['name', 'account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cash_account_name_per_account', 'cash_account', type_='unique')
    # ### end Alembic commands ###
