"""Your changes

Revision ID: 081f12de1175
Revises: 00787eedb53f
Create Date: 2025-04-04 09:50:46.212441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081f12de1175'
down_revision: Union[str, None] = '00787eedb53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_name_key', 'category', type_='unique')
    op.create_unique_constraint('uq_category_name_per_account', 'category', ['name', 'account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_per_account', 'category', type_='unique')
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    # ### end Alembic commands ###
