"""Your changes

Revision ID: 19076e9615ca
Revises: 283987768536
Create Date: 2025-03-30 14:21:12.199756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19076e9615ca'
down_revision: Union[str, None] = '283987768536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('base_type', sa.Enum('INCOME', 'EXPENSIVE', name='transactiontype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'base_type')
    # ### end Alembic commands ###
