"""added lenth

Revision ID: 28014738ee66
Revises: ad3524ae0676
Create Date: 2025-04-11 16:57:39.421271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28014738ee66'
down_revision: Union[str, None] = 'ad3524ae0676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'symbol',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('currency', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.alter_column('currency', 'symbol',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
