"""increase rate precise

Revision ID: 2d6027890139
Revises: cd2ea2bd3699
Create Date: 2025-04-21 20:16:00.695440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6027890139'
down_revision: Union[str, None] = 'cd2ea2bd3699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'rate',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'rate',
               existing_type=sa.Numeric(precision=15, scale=8),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
