"""Your changes

Revision ID: 9020aae082ef
Revises: cff839ef5f5c
Create Date: 2025-04-08 01:28:44.009460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9020aae082ef'
down_revision: Union[str, None] = 'cff839ef5f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('hour', sa.Integer(), server_default='0', nullable=False))
    op.add_column('reminder', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('reminder', 'is_acitve')
    op.drop_column('reminder', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('reminder', sa.Column('is_acitve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('reminder', 'is_active')
    op.drop_column('reminder', 'hour')
    # ### end Alembic commands ###
