"""empty message

Revision ID: b16d0e6a90ff
Revises: 76361824b825
Create Date: 2025-03-20 01:26:50.640300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b16d0e6a90ff"
down_revision: Union[str, None] = "76361824b825"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=3), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exchange_rate",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_currency_id", sa.Integer(), nullable=False),
        sa.Column("to_currency_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_id"],
            ["currency.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "cash_account", sa.Column("currency_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "cash_account", "currency", ["currency_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cash_account", type_="foreignkey")
    op.drop_column("cash_account", "currency_id")
    op.drop_table("exchange_rate")
    op.drop_table("currency")
    # ### end Alembic commands ###
