"""Your changes

Revision ID: b80bc25dc7f5
Revises:
Create Date: 2025-03-26 01:40:04.420735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b80bc25dc7f5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category", "account_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "operations", sa.Column("cash_account_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "operations",
        sa.Column("to_cash_account_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "operations_to_account_id_fkey", "operations", type_="foreignkey"
    )
    op.drop_constraint(
        "operations_account_id_fkey", "operations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "operations", "cash_account", ["cash_account_id"], ["id"]
    )
    op.create_foreign_key(
        None, "operations", "cash_account", ["to_cash_account_id"], ["id"]
    )
    op.drop_column("operations", "to_account_id")
    op.drop_column("operations", "account_id")
    op.alter_column(
        "reminder", "account_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reminder", "account_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "operations",
        sa.Column(
            "account_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "operations",
        sa.Column(
            "to_account_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "operations", type_="foreignkey")
    op.drop_constraint(None, "operations", type_="foreignkey")
    op.create_foreign_key(
        "operations_account_id_fkey",
        "operations",
        "account",
        ["account_id"],
        ["id"],
    )
    op.create_foreign_key(
        "operations_to_account_id_fkey",
        "operations",
        "account",
        ["to_account_id"],
        ["id"],
    )
    op.drop_column("operations", "to_cash_account_id")
    op.drop_column("operations", "cash_account_id")
    op.alter_column(
        "category", "account_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
