"""Your changes

Revision ID: cd2ea2bd3699
Revises: 30cd4647d315
Create Date: 2025-04-18 10:40:44.707174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2ea2bd3699'
down_revision: Union[str, None] = '30cd4647d315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('admin', sa.BOOLEAN(), server_default='false', nullable=True))
    op.add_column('operations', sa.Column('exchange_rate', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('operations', sa.Column('linked_operation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operations', 'operations', ['linked_operation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'linked_operation_id')
    op.drop_column('operations', 'exchange_rate')
    op.drop_column('account', 'admin')
    # ### end Alembic commands ###
