"""set main to default false

Revision ID: cff839ef5f5c
Revises: 
Create Date: 2025-04-06 23:32:55.236622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff839ef5f5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cash_account_main_per_account', 'cash_account', type_='unique')
    op.create_index('ix_unique_main_account', 'cash_account', ['account_id'], unique=True, postgresql_where=sa.text('main = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_main_account', table_name='cash_account', postgresql_where=sa.text('main = true'))
    op.create_unique_constraint('uq_cash_account_main_per_account', 'cash_account', ['main', 'account_id'])
    # ### end Alembic commands ###
