"""Your changes

Revision ID: dc948e6888b4
Revises: 30cd4647d315
Create Date: 2025-04-13 20:41:57.582984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc948e6888b4'
down_revision: Union[str, None] = '30cd4647d315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'cash_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'cash_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
