"""symbol native

Revision ID: ff3b2cc7660a
Revises: 1ba354df14ba
Create Date: 2025-04-11 17:58:33.876340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3b2cc7660a'
down_revision: Union[str, None] = '1ba354df14ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('symbol_native', sa.VARCHAR(length=255), nullable=True))
    op.create_unique_constraint(None, 'currency', ['symbol_native'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency', type_='unique')
    op.drop_column('currency', 'symbol_native')
    # ### end Alembic commands ###
